---
wordpress_mysql_host: "localhost"
wordpress_mysql_db: "wordpress"
wordpress_mysql_user: "wordpress"
wordpress_mysql_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66656661383165646430643835636235373132366661323064336563356533393266666666373832
  6564383161663837353834383538333837323136653966650a323431326665643332313331653465
  34356539313834363239303263333130326539353336303635313034373437316239336434646437
  6534653066326633630a306362353939323465366166643062303637323435376665313033393237
  31386637336438643336616533393634303933353736646164663062303131333264653930613661
  3639316430633537626536303531613630633936336531303265

wordpress_path: "/srv"
wordpress_servername: "localhost"
wordpress_home_url: "http://127.0.0.1"
wordpress_site_title: "Mon Premier Blog"

wordpress_admin_user: "admin"
wordpress_admin_user_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37613631663936653639343031613732343037386335356165623733376661353938623434653338
  6137646130363536376435326635616332326337363230360a636634333139363533316537613232
  37643661313166333438333239393439363038653033343266623264376334396632646130663862
  3864393636363063640a393838343737333430653939396432303633636662336562653633383966
  3237

wordpress_admin_email: "noreply@domain.tld"

wordpress_http_server: nginx
