---
- name: Download WordPress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: "0644"
    validate_certs: false
  failed_when: false

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wordpress_path }}"
    copy: false
