---
- name: Add configuration to Apache
  ansible.builtin.template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-enabled/wordpress.conf
    mode: "0644"
  notify: Restart apache2
  when: wordpress_http_server == "apache2"

- name: Add configuration to nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/wordpress
    mode: "0644"
  notify: Restart nginx
  when: wordpress_http_server == "nginx"
