---
- name: Install

  hosts: 
    - test

  tasks:
    - name: Deploy Mysql
      ansible.builtin.import_role:
        name: mariadb

    - name: Deploy Nginx
      ansible.builtin.import_role:
        name: nginx

    - name: Deploy Magento
      ansible.builtin.import_role:
        name: magento
